services:
  - type: web
    name: shah-prices
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --timeout 120 --workers 1 --bind 0.0.0.0:$PORT server:app
    plan: free
